/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import slug from "custom-slug/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import tagsinput from "strapi-plugin-tagsinput/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "color-picker": colorPicker,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    slug: slug,
    "import-export-entries": importExportEntries,
    tagsinput: tagsinput,
  },
});
